owner: hcpss # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Canvas
    url: https://hcpss.instructure.com/courses/34447
  - name: Microsoft
    url: https://www.office.com/
  - name: Google
    url: https://drive.google.com/
  - name: Clever
    url: https://clever.com/in/hcpss/?skip=1&specify_auth=saml
  - name: Workday
    url: https://www.myworkday.com/wday/authgwy/hcpss/login.htmld
  - name: Synergy (Staff)
    url: https://critical-status.hcpss.org/edupoint-staff
  - name: Synergy (Students/Parents)
    url: https://critical-status.hcpss.org/edupoint-parents
  - name: Duo
    url: https://api-a01cc0d2.duosecurity.com/
  - name: S/SAM
    url: https://sam.hcpss.org/api/docs/
  - name: Account Self-Service
    url: https://account.hcpss.org/api/docs/
  - name: SSO
    url: https://hcpss.me/saml/saml2/idp/metadata.php
  - name: Active Directory (HCPSS)
    url: https://critical-status.hcpss.org/hcpss
  - name: Active Directory (INST)
    url: https://critical-status.hcpss.org/inst

assignees:
  - nickadam

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/HCPSS/upptime/master/assets/hcpss.svg
  name: Status
  introTitle: HCPSS Asynchronous Instructional Services Status
  introMessage: These services are checked once every five minutes. Past incident details are listed at the bottom of the page.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
